### ISSUE TITLE
Incompatibility with Disenchanter Mod

### ISSUE THREAD

**Issue by D3nnis3n** [TominoCZ/FancyBlockParticles#15]
I'll just link the issue at Disenchanter Mod to you and hope you know what is wrong:
https://github.com/Impelon/Disenchanter/issues/21#issuecomment-334421976

**Comment by Impelon** [comment]
Sooou... I'm the author of Disenchanter.
Apparently, if FancyBlockParticles and Disenchanter are both installed in 1.12.2 the Texture of the Disenchantment Table goes invisible. I'm doing some hacky stuff when registering the blockstate-model (see  Impelon/Disenchanter#12), maybe that's the cause?

If I can help somehow to resolve this issue... ^^

**Comment by TominoCZ** [comment]
It's not removing the mod that fixes this bug.. it fixes itself when you reload the world. It is because what my mod does is that it gets the IBakedModel from the block and I re-bake it, rotate it's position vertices and finally render it. I think the rotation might have messed it up.. I'm not too sure. The code for re-baking the model isn't my own.

Also you can add this block to exceptions for the block placing animation in the Fancy Block Particles menu, so there's nothing you both need to really worry about.
