### ISSUE TITLE
[Request] Remove effects

### ISSUE THREAD

**Issue by GWSheridan** [TominoCZ/FancyBlockParticles#32]
I might of missed this some where but will ask for feature just incase
Some blocks give off effects in the world like torches when placed have the the nice fancy smoke an flame. 
Could there be an option to turn them off for some blocks as when theres a lot of them FPS drops a fair bit.

If i have missed this option my bad

**Comment by TominoCZ** [comment]
So.. you mean you want to disable the smoke and flame particles only for specific blocks?

**Comment by GWSheridan** [comment]
ye that would be great. Ash blocks from BoP destroy frames when in the nether

**Comment by TominoCZ** [comment]
That unfortunatly isn't possible to do... My mod only detects when a smoke particles is about to spawn and then instead of spawning the vanilla one, I spawn my fancy particle. 

There is no way for my mod to change whether the smoke particles will spawn or not. My particles function just like vanilla particles, only look different. So disabling my particles would be just like disabling vanilla particles to spawn.. 

I hope you understand what I mean... The maker of BoP would have to add an option to disable smoke particles.

**Comment by GWSheridan** [comment]
no problem understand that thanks
