### ISSUE TITLE
Exceptions are not saved

### ISSUE THREAD

**Issue by Zsashas** [TominoCZ/FancyBlockParticles#38]
For example, setting TiCon stone torches to not use fancy placement, the next time I load up the game they are back to using it again, and I have to re-disable it.

**Comment by Zsashas** [comment]
Ok, apparently it's worse than that. The config gets reset to the default every time the game is loaded. There is no way to set exceptions for more than a single session.

**Comment by TominoCZ** [comment]
Hmm.. the only reason I can think of why this is happening is that I load the exceptions before the blocks are even registered..
My mod checks the block exceptions for blocks that aren't in the registry and by doing so before everything is registered, the mod thinks that the block is not in the registry so it gets removed.

Should be fixed in the next version :)
