### ISSUE TITLE
Water physics not that realistic

### ISSUE THREAD

**Issue by Eddi2015** [TominoCZ/FancyBlockParticles#62]
## What went wrong:
Some blocks use water physics when they shouldn't and the other way round:
  Blocks that **shouldn't** use water physics:
  
-  redstone repater
-   redstone comperator
-   weighted pressure plate (golden)
-   weighted pressure plate (silver)
-   lever (because of cobblestone-like particles)
-   probably more?

  Blocks that **should** (IMO) have water physics:
   
-    lilypads
-    vines
-    saplings
-    Cobwebs?
-    fern
-    grass
-    ladder (because of wooden particles)
-    leaves
-    flowers
-   sugar cane
-   peony
-   ice (packed and none packed)
-   wheat
-    probably more?

## What was expected:
an option to define which blocks use water physics, similiar to the block-exception one.
## Steps to reproduce issue:
Break those blocks
## MC Version:
1.8.9
## FBP Version:
2.3.8 (btw. 2.3.9 isn't released on curseforge yet)
## Forge Version (e.g. 2604):
2318

**Comment by TominoCZ** [comment]
Ok.. I think you want a little too much.. The blocks you mentioned don't share a variable that I could use for detecting whether they are wooden or not. Adding another list of exceptions would be a little too overkill.

The water physics work on blocks of wood material or blocks with wood step sound. The wood step sound is most likely messing it up.

I will fix it once I have something reasonable to add to the mod so that I can release it for all versions. It seems like a nonsense to me to release a new version with just one tiny bugfix, so I'll release it once I add more stuff.

Nontheless, this will be fixed in the next version.
