### ISSUE TITLE
[BUG]Place animation could make IC block invalid

### ISSUE THREAD

**Issue by Tollainmear** [TominoCZ/FancyBlockParticles#75]
## Steps to reproduce issue:
* Enable the place animation
* then place a IC2 block (such as MFSU)
* Then it happened
![](https://raw.githubusercontent.com/Tollainmear/PicRepo/master/bugissuePics/FBP/2.png)
* But if we set `fancyPlaceAnim` to false, that situation has never appeared

**Comment by TominoCZ** [comment]
Yes. This feature is never going to be perfect and that is one of the reason it is disabled by default and is described as a feature in an Alpha stage. 

Since i know it isn't, perfect, there is a feature that lets you add specific blocks to exceptions for either the placement animation or the particles spawning. Simply hold 'X' while looking at the specific block and then move that slider towards the placement animation circle. That will add make it so that this block doesn't have the placement animation(until you enable it back the same way).

Lastly, Fancy Block Particles is a Cosmetic mod. Cosmetic mods are not for servers.

**Comment by Tollainmear** [comment]
Sure, thanks for your reply, I got that.
You are a responsible developer. I should pay my respects to you and learn from you ;)
