### ISSUE TITLE
IC2 cable of any kind gives off purple/black particles

### ISSUE THREAD

**Issue by Tyler799** [TominoCZ/FancyBlockParticles#8]
Here's an image: https://imgur.com/a/JSzDc

**Comment by TominoCZ** [comment]
what minecraft version is this screenshot from?

**Comment by Tyler799** [comment]
This is MC 1.10.2, latest version of FBP and IC2 Exp.

**Comment by TominoCZ** [comment]
I found out that it is actually a bug in IC2, also because my mod automatically fixes missing textures for the particle. So if there's a missing texture, it's not FBP'sd fault :)

**Comment by Tyler799** [comment]
The texture isn't missing though. The cable looks completely normal.

**Comment by TominoCZ** [comment]
That is not the matter. Every block has it's own state, which should also carry data about the texture. All breaking particles have to use the block state to get the block's texture. 
So the problem here is that particles get a corrupt/incomplete block state(caused by IC2) from which they try to get the texture.
