### ISSUE TITLE
Particles appear transparent and flash between transparent/opaque when viewed from certain angles.

### ISSUE THREAD

**Issue by KimJongUninstall** [TominoCZ/FancyBlockParticles#84]
## Steps to reproduce issue:
Not entirely sure how to reproduce this. I originally assumed it was Optifine, given how infamous it is for changing rendering code, but removing it didn't resolve the issue. I don't have any shaders or other mods which change rendering code.
## MC Version:
Minecraft 1.12.2
## FBP Version:
FBP 2.4.0
## Forge Version (e.g. 2604):
Forge 14.23.3.2681

**Comment by TominoCZ** [comment]
Send a screenshot if you can please.  Does enabling/disabling VBOs fix it?

**Comment by KimJongUninstall** [comment]
![2018-05-13_14 24 19](https://user-images.githubusercontent.com/39226074/39970433-6a133d0a-56b9-11e8-827e-f474246cac95.png)
I tried disabling VBOs, didn't fix the issue. Here's what it looks like.

**Comment by SextupleTap** [comment]
Do the mods you have consist of only: "Mo' bends, Optifine, and FBP?"

If not a full mod list or the game logs could be useful (as a gist or on a paste site)...

**Comment by SextupleTap** [comment]
Well the game logs would also be useful to have along with the mod list.

**Comment by KimJongUninstall** [comment]
sorry, Here's the latest game log. https://pastebin.com/YmAXzUYK

**Comment by Noxalas** [comment]
I'm experiencing the same exact problem,
tried to put this mod into my modpack and it happened to me too.

I also tried to put one mod at a time in, using KimJong's modlist as a reference for what mods may be causing it, but I didn't manage to find the specific mod causing it.

I have realized that it most probably has something to do with entities, though, because the bug is only in effect whenever I look in the direction of one.

Here's my list of mods at which point the bug starts to happen: https://pastebin.com/cvLnEyy8
(I normally have a lot more in this modpack.)

**Comment by SextupleTap** [comment]
Could it be FoamFix?

**Comment by TominoCZ** [comment]
I am not entirely sure what could be causing this issue.. Did you guys try running FBP alone?

I am rewriting the mod in the rendering areas so it might get fixed in the next update.

**Comment by TominoCZ** [comment]
Yeah.. I think this will be fixed in the next version.
Thanks for the info

**Comment by TominoCZ** [comment]
See if it works in 2.4.1 please.

**Comment by Electrosynthesis** [comment]
I did a quick test using a similar setup to before with the Familiar Fauna Pixie and there were no rendering problems with the fancy block particles. Thanks for the fix!

**Comment by TominoCZ** [comment]
Np ;)
